feat: add RelationPropertyValue
makenotion/notion-sdk-js pull request #166
Opened 2021-08-03 23:48 UTC by jack-michaud

Adds `RelationPropertyValue` to `PropertyValue`, as defined by [Relation Property value (developers.notion.com)](https://developers.notion.com/reference/page#relation-property-values) 

Fixes #165
![image](https://user-images.githubusercontent.com/13189762/128100127-33dd22a9-502d-4801-afc7-1fdca8b3a543.png)

2021-08-03 23:49 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/makenotion/notion-sdk-js?pullRequest=166) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/makenotion/notion-sdk-js?pullRequest=166) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/makenotion/notion-sdk-js?pullRequest=166) it.</sub>

2021-09-08 23:11 UTC, nishadagrawal commented
Hi @jack-michaud, thanks for contributing! 🎉  
This change looks good to me, can you please just update the branch and then we will merge it in?

2021-09-09 16:29 UTC, nishadagrawal requested changes
sending back to update the branch. Thanks!

2021-09-09 22:36 UTC, jack-michaud commented
Looks like this feature was merged in by someone else: https://github.com/makenotion/notion-sdk-js/pull/185

Too bad for me :slightly_smiling_face:

2021-09-09 22:36 UTC, closed without merging